FROM node:18.16.0-alpine AS builder

WORKDIR /app

COPY package*.json .

RUN npm install --production

COPY . .

RUN npm run build

# Production NGINX Image below

FROM nginx

COPY --from=builder /app/build usr/share/nginx/html
